name: YuPball
main: com.myxcoding.yupie_123.YuPball
author: MyxCoding
version: 1.0
description: >
             A plugin created for yupie_123 by MyxCoding Limited.
softdepend: [Nametag]
depend: [TagAPI]
website: http://www.myxgaming.com/

commands:
  warn:
    description: Warns a player
  staff:
    description: Displays staff online
  points:
    description: Displays your points
  shop:
    description: Displays the shop
  yb:
    description: Displays Information about the plugin
  join:
    description: Displays Information about the plugin
  leave:
    description: Displays Information about the plugin
  stats:
    description: Displays Information about the plugin
  set:
    description: Allows you to set the Lobby position and the Spectator position