name: YuPball
main: com.myxcoding.yupie_123.YuPball
version: 1.0
description: >
             A plugin created for yupie_123 by MyxCoding Limited.
commands:
  red:
    description: Adds you to the red team!
    usage: /red
  blue:
    description: Adds you to the blue team!!
    usage: /blue
  warn:
    description: Warns a player and adds to their infractions! Once they reach five infractions they shall be banned!
    usage: /warn <player_name>
  points:
    description: Shows you your points!
    usage: /points [Player]
  yb:
    description: The base command for the plugin
    usage: /yb
  pl:
    description: Alias for YB 
    usage: /pl
  plugins:
    description: Alias for YB
    usage: /plugins
  staff:
    description: Dispays the servers staff and the staff currently online!
    usage: /staff
  shop:
    description: Displays the shop!
    usage: /shop